### ISSUE TITLE
add CLI to `scripts/cook`

### ISSUE THREAD

**Issue by fernandogelin** [compbiocore/refchef#4]
The CLI section of the package should go to `scripts/cook`. This is already set up in `setup.py`.

**Comment by fernandogelin** [comment]
@andrew-leith I don't think the argument `--master` should be present and required. If the user is running ref chef for the first time they won't have a master yaml. And if they have a master.yaml already, the script should get the file location form the path or GitHub repo specified in the config file.

**Comment by andrew-leith** [comment]
I'm not sure I fully agree on this count.  When there is no YAML at all on the system, the first YAML that is created by the user will be the master YAML by definition, to which future entries will be appended; thus, there will always be a file serving as the master YAML no matter what.  The alternative is to make the new YAML required, since there will always be _some_ YAML, however you designate it, but that will require changing the underlying logic only to put us in effectively the same place.  Ashok and I have talked about this before - maybe we should schedule a meeting with all 3 of us after the DSP meeting on Tuesday?

To be less abstract, I don't disagree about removing --master as a CLI argument and instead having its location determined entirely by the config file; I merely disagree with the principle of not requiring something designated as the master YAML to always exist.  In fact, I _agree_ that putting it in the config file is better since the master YAML will (ideally) always be at the same filepath for a given system, and not having to retype it every time you run the parser is far more efficient / robust against typographical errors.  I think we just need to be very clear on the definitions and underlying logic of how the parser operates before we release anything.
